# Generated by Django 4.1.1 on 2022-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('RequestId', models.AutoField(primary_key=True, serialize=False)),
                ('RequesterEmailid', models.EmailField(max_length=254)),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('FlexibleDate', models.BooleanField(default=False)),
                ('TotalAssets', models.IntegerField()),
                ('AssetType', models.CharField(max_length=10)),
                ('AssetSenstivity', models.CharField(max_length=20)),
                ('DeliveryContact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('RiderId', models.AutoField(primary_key=True, serialize=False)),
                ('RiderEmailid', models.EmailField(max_length=254)),
                ('RiderContact', models.IntegerField()),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('FlexibleDate', models.BooleanField(default=False)),
                ('Medium', models.CharField(max_length=5)),
                ('TotalAssets', models.IntegerField()),
                ('AssetType', models.CharField(max_length=10)),
                ('AssetSenstivity', models.CharField(max_length=20)),
                ('DeliveryContact', models.IntegerField()),
            ],
        ),
    ]
