# Generated by Django 4.1.2 on 2022-10-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsRideServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='AssetSenstivity',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='AssetType',
        ),
        migrations.RemoveField(
            model_name='riders',
            name='AssetSenstivity',
        ),
        migrations.RemoveField(
            model_name='riders',
            name='AssetType',
        ),
        migrations.RemoveField(
            model_name='riders',
            name='DeliveryContact',
        ),
        migrations.AddField(
            model_name='requests',
            name='Assetsensitivity',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Sensitive', 'Sensitive'), ('Highly Sensitive', 'Highly Sensitive')], default='Normal', max_length=25),
        ),
        migrations.AddField(
            model_name='requests',
            name='RequesterDate',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='requests',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='riders',
            name='Medium',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Car', 'Car'), ('Train', 'Train')], max_length=5),
        ),
        migrations.AddField(
            model_name='requests',
            name='Assettype',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('TravelBag', 'Travel Bag'), ('Package', 'Package')], default='Laptop', max_length=25),
        ),
    ]
