# Generated by Django 4.1.2 on 2022-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsRideServer', '0002_remove_requests_assetsenstivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='RiderDate',
            field=models.IntegerField(default=10),
        ),
    ]
